#!/usr/bin/env bash
# install nginx web server

sudo apt-get update && upgrade
sudo apt-get install nginx -y

#Create a directory called html inside your nginx server
sudo mkdir -p /var/www/html
#Create a file inside that directory called index.html
sudo touch /var/www/html/index.html
#Display your message then
sudo echo "Holberton School" | sudo tee /var/www/html/index.html

sudo sed -i "24i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default

sudo service nginx restart
